---
- name: Change mongo config file
  template:
    src: mongod.conf.j2 # <-- По умолчанию ищется в папке templates
    dest: /etc/mongod.conf # <-- Путь на удаленном хосте
    mode: 0644 # <-- Права на файл, которые нужно установить
  notify: restart mongod