---
- name: Add APT key
  apt_key:
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4
    keyserver: keyserver.ubuntu.com
  tags: install   
  
# Подключаем репозиторий с пакетами mongodb    
- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
    state: present
  tags: install       

# Выполним установку пакета
- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: install       

# Включаем сервис
- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install 