---
    - name: Deploy application # <-- Словесное описание сценария (name)
      hosts: app # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
      tags: deploy-tag
      tasks: # <-- Блок тасков (заданий), которые будут выполняться для данных хостов
        - name: Fetch the latest version of application code
          git:
            repo: 'https://github.com/express42/reddit.git'
            dest: /home/appuser/reddit
            version: monolith # <-- Указываем нужную ветку
          notify: reload puma
          
        - name: Bundle install
          bundler:
            state: present
            chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle
          
      handlers:   # <-- Добавим блок handlers и задачу
        - name: reload puma
          become: true
          systemd: name=puma state=restarted