---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  #playbooks:
  #  create: create.yml
  #  converge: converge.yml
  #  destroy: destroy.yml
#verifier:
#  name: testinfra
#  lint:
#    name: flake8
